export const books = [
  {
    id: 1,
    title: "ninja education book",
    author: "ninjawanko",
    genre: "education",
    publishedYear: 2010,
  },
  {
    id: 2,
    title: "baby life style",
    author: "baby",
    genre: "comics",
    publishedYear: 2011,
  },
  {
    id: 3,
    title: "wooly's journey",
    author: "wooly",
    genre: "fiction",
    publishedYear: 2012,
  },
  {
    id: 4,
    title: "hidden forest academy",
    author: "flora",
    genre: "education",
    publishedYear: 2013,
  },
  {
    id: 5,
    title: "astro adventures",
    author: "comet",
    genre: "fiction",
    publishedYear: 2014,
  },
  {
    id: 6,
    title: "puzzle chronicles",
    author: "veil",
    genre: "comics",
    publishedYear: 2015,
  },
  {
    id: 7,
    title: "ancient minds",
    author: "sage",
    genre: "education",
    publishedYear: 2016,
  },
  {
    id: 8,
    title: "quantum quirk",
    author: "quanty",
    genre: "fiction",
    publishedYear: 2017,
  },
  {
    id: 9,
    title: "robot rebels",
    author: "cogmaster",
    genre: "comics",
    publishedYear: 2018,
  },
  {
    id: 10,
    title: "growth blueprint",
    author: "savvy",
    genre: "education",
    publishedYear: 2019,
  },
];
